In [24]:
import numpy as nump #I can define how I import my Numpy

x = nump.full((6,6), 25)

print(x)

print()

y = nump.zeros([2,2], dtype=int)

print(y)

print()

xx = x.copy()

print(xx)

xx[3:5,3:5] = y

print()

z = nump.full((3,3), -4)

print(z)

xx[-6:-3,-6:-3] = z

print()

print(xx)

[[25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]]

[[0 0]
 [0 0]]

[[25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]]

[[-4 -4 -4]
 [-4 -4 -4]
 [-4 -4 -4]]

[[-4 -4 -4 25 25 25]
 [-4 -4 -4 25 25 25]
 [-4 -4 -4 25 25 25]
 [25 25 25  0  0 25]
 [25 25 25  0  0 25]
 [25 25 25 25 25 25]]


In [25]:
xx + 15

array([[11, 11, 11, 40, 40, 40],
       [11, 11, 11, 40, 40, 40],
       [11, 11, 11, 40, 40, 40],
       [40, 40, 40, 15, 15, 40],
       [40, 40, 40, 15, 15, 40],
       [40, 40, 40, 40, 40, 40]])

In [26]:
xx - 15

array([[-19, -19, -19,  10,  10,  10],
       [-19, -19, -19,  10,  10,  10],
       [-19, -19, -19,  10,  10,  10],
       [ 10,  10,  10, -15, -15,  10],
       [ 10,  10,  10, -15, -15,  10],
       [ 10,  10,  10,  10,  10,  10]])

In [27]:
xx * 15

array([[-60, -60, -60, 375, 375, 375],
       [-60, -60, -60, 375, 375, 375],
       [-60, -60, -60, 375, 375, 375],
       [375, 375, 375,   0,   0, 375],
       [375, 375, 375,   0,   0, 375],
       [375, 375, 375, 375, 375, 375]])

In [28]:
xx / 15

array([[-0.26666667, -0.26666667, -0.26666667,  1.66666667,  1.66666667,
         1.66666667],
       [-0.26666667, -0.26666667, -0.26666667,  1.66666667,  1.66666667,
         1.66666667],
       [-0.26666667, -0.26666667, -0.26666667,  1.66666667,  1.66666667,
         1.66666667],
       [ 1.66666667,  1.66666667,  1.66666667,  0.        ,  0.        ,
         1.66666667],
       [ 1.66666667,  1.66666667,  1.66666667,  0.        ,  0.        ,
         1.66666667],
       [ 1.66666667,  1.66666667,  1.66666667,  1.66666667,  1.66666667,
         1.66666667]])

In [29]:
xx // 15

array([[-1, -1, -1,  1,  1,  1],
       [-1, -1, -1,  1,  1,  1],
       [-1, -1, -1,  1,  1,  1],
       [ 1,  1,  1,  0,  0,  1],
       [ 1,  1,  1,  0,  0,  1],
       [ 1,  1,  1,  1,  1,  1]], dtype=int32)

In [30]:
xx + x

array([[21, 21, 21, 50, 50, 50],
       [21, 21, 21, 50, 50, 50],
       [21, 21, 21, 50, 50, 50],
       [50, 50, 50, 25, 25, 50],
       [50, 50, 50, 25, 25, 50],
       [50, 50, 50, 50, 50, 50]])

In [32]:
xx - x

array([[-29, -29, -29,   0,   0,   0],
       [-29, -29, -29,   0,   0,   0],
       [-29, -29, -29,   0,   0,   0],
       [  0,   0,   0, -25, -25,   0],
       [  0,   0,   0, -25, -25,   0],
       [  0,   0,   0,   0,   0,   0]])

In [33]:
xx ** 3

array([[  -64,   -64,   -64, 15625, 15625, 15625],
       [  -64,   -64,   -64, 15625, 15625, 15625],
       [  -64,   -64,   -64, 15625, 15625, 15625],
       [15625, 15625, 15625,     0,     0, 15625],
       [15625, 15625, 15625,     0,     0, 15625],
       [15625, 15625, 15625, 15625, 15625, 15625]], dtype=int32)

In [34]:
x ** 9

array([[766306777, 766306777, 766306777, 766306777, 766306777, 766306777],
       [766306777, 766306777, 766306777, 766306777, 766306777, 766306777],
       [766306777, 766306777, 766306777, 766306777, 766306777, 766306777],
       [766306777, 766306777, 766306777, 766306777, 766306777, 766306777],
       [766306777, 766306777, 766306777, 766306777, 766306777, 766306777],
       [766306777, 766306777, 766306777, 766306777, 766306777, 766306777]],
      dtype=int32)

In [36]:
nump.sin(z)

array([[0.7568025, 0.7568025, 0.7568025],
       [0.7568025, 0.7568025, 0.7568025],
       [0.7568025, 0.7568025, 0.7568025]])

In [37]:
nump.sin(xx)

array([[ 0.7568025 ,  0.7568025 ,  0.7568025 , -0.13235175, -0.13235175,
        -0.13235175],
       [ 0.7568025 ,  0.7568025 ,  0.7568025 , -0.13235175, -0.13235175,
        -0.13235175],
       [ 0.7568025 ,  0.7568025 ,  0.7568025 , -0.13235175, -0.13235175,
        -0.13235175],
       [-0.13235175, -0.13235175, -0.13235175,  0.        ,  0.        ,
        -0.13235175],
       [-0.13235175, -0.13235175, -0.13235175,  0.        ,  0.        ,
        -0.13235175],
       [-0.13235175, -0.13235175, -0.13235175, -0.13235175, -0.13235175,
        -0.13235175]])

In [41]:
nump.arccosh(xx)

C:\Users\padra\AppData\Local\Temp/ipykernel_33248/2417367193.py:1: RuntimeWarning: invalid value encountered in arccosh
  nump.arccosh(xx)


array([[       nan,        nan,        nan, 3.91162277, 3.91162277,
        3.91162277],
       [       nan,        nan,        nan, 3.91162277, 3.91162277,
        3.91162277],
       [       nan,        nan,        nan, 3.91162277, 3.91162277,
        3.91162277],
       [3.91162277, 3.91162277, 3.91162277,        nan,        nan,
        3.91162277],
       [3.91162277, 3.91162277, 3.91162277,        nan,        nan,
        3.91162277],
       [3.91162277, 3.91162277, 3.91162277, 3.91162277, 3.91162277,
        3.91162277]])

In [42]:
nump.tanh(x)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
nump.cosh(x)

array([[3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10],
       [3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10],
       [3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10],
       [3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10],
       [3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10],
       [3.60024497e+10, 3.60024497e+10, 3.60024497e+10, 3.60024497e+10,
        3.60024497e+10, 3.60024497e+10]])

In [44]:
nump.arcsin(x)

C:\Users\padra\AppData\Local\Temp/ipykernel_33248/2259309809.py:1: RuntimeWarning: invalid value encountered in arcsin
  nump.arcsin(x)


array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [45]:
nump.arccos(x)

C:\Users\padra\AppData\Local\Temp/ipykernel_33248/2505263134.py:1: RuntimeWarning: invalid value encountered in arccos
  nump.arccos(x)


array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

#### Linear Algebra

In [46]:
nump.matmul(xx,x) #Matrix multiplication function

array([[1575, 1575, 1575, 1575, 1575, 1575],
       [1575, 1575, 1575, 1575, 1575, 1575],
       [1575, 1575, 1575, 1575, 1575, 1575],
       [2500, 2500, 2500, 2500, 2500, 2500],
       [2500, 2500, 2500, 2500, 2500, 2500],
       [3750, 3750, 3750, 3750, 3750, 3750]])

In [48]:
m = nump.full((5,4), 6)
print(m)

print()

n = nump.ones((4,5), dtype=int)
print(n)

nump.matmul(m,n) #Matrix multiplication function



[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

In [8]:
# To get the determinant
import numpy as nump
a = nump.identity(4)
nump.linalg.det(a)

1.0

In [10]:
# To get the determinant
import numpy as nump
b = nump.full((5,5),4)
print(b)
nump.linalg.det(b)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


0.0

In [16]:
# To get the determinant
import numpy as nump
c = nump.array([[-2.9,-3,1.4,0],[30,-21,45,-99],[1.2,0.8,6.6,-0.9],[-12.5,5.12,7.8,-0.4]])
print(c)
nump.linalg.det(c)

[[ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]]


-34790.84760000007

In [17]:
d = nump.random.rand(7,7)
print(d)

[[0.49850983 0.35865804 0.85475488 0.48012334 0.42800864 0.74398958
  0.19870495]
 [0.78287065 0.97610571 0.10182839 0.61931154 0.40526144 0.29820378
  0.0817797 ]
 [0.6353672  0.68895193 0.90257909 0.30703593 0.78464232 0.27933266
  0.48708152]
 [0.96712153 0.48361815 0.60666707 0.9564149  0.63556797 0.06901329
  0.00715838]
 [0.18256116 0.85840081 0.79969689 0.51300493 0.44565772 0.94854012
  0.58569436]
 [0.12709345 0.79803012 0.95117599 0.30083282 0.55949562 0.06691121
  0.0392776 ]
 [0.82589355 0.38705345 0.73064163 0.07560433 0.5613676  0.44925367
  0.95749938]]


In [18]:
nump.linalg.det(d)

0.045232410859446535

#### Statistics

In [19]:
nump.min(d) #minimum value in the array

0.007158379320868713

In [20]:
nump.max(d) #minimum value in the array

0.9761057139941152

In [21]:
nump.min(d, axis = 1) 

array([0.19870495, 0.0817797 , 0.27933266, 0.00715838, 0.18256116,
       0.0392776 , 0.07560433])

In [24]:
nump.max(d, axis = 1)

array([0.85475488, 0.97610571, 0.90257909, 0.96712153, 0.94854012,
       0.95117599, 0.95749938])

In [25]:
nump.sum(d) #Sum of all the values in the array.

25.80234882557734

#### Reorganising Arrays

In [29]:
before = nump.array([[2,3,-4],[1,0,-2],[6,-3,4]])
print(before)
before.shape

[[ 2  3 -4]
 [ 1  0 -2]
 [ 6 -3  4]]


(3, 3)

In [30]:
before = nump.array([[2,3,-4],[1,0,-2],[6,-3,4]])
before
before.shape

(3, 3)

In [32]:
after = before.reshape((3,2))
print(after)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [34]:
before1 = nump.array([[2,3,-4],[1,0,-2]])
print(before1)
before1.shape

[[ 2  3 -4]
 [ 1  0 -2]]


(2, 3)

In [35]:
after = before1.reshape((3,2))
print(after)

[[ 2  3]
 [-4  1]
 [ 0 -2]]


In [37]:
after = before1.reshape((5,1))
print(after)

ValueError: cannot reshape array of size 6 into shape (5,1)

In [50]:
#Vertically stacking vectors
e = nump.random.rand(4,4)
print(e)

print()

print(c)

print()

nump.vstack([e,c])

print()

print(nump.vstack([e,c]))

[[0.05156942 0.48036936 0.8918268  0.22543258]
 [0.6852451  0.74691728 0.10884937 0.41985718]
 [0.98914143 0.70126818 0.17833877 0.40553427]
 [0.81901574 0.95650993 0.74965551 0.68873769]]

[[ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]]


[[ 5.15694242e-02  4.80369363e-01  8.91826801e-01  2.25432580e-01]
 [ 6.85245103e-01  7.46917277e-01  1.08849370e-01  4.19857185e-01]
 [ 9.89141431e-01  7.01268176e-01  1.78338767e-01  4.05534271e-01]
 [ 8.19015736e-01  9.56509926e-01  7.49655514e-01  6.88737689e-01]
 [-2.90000000e+00 -3.00000000e+00  1.40000000e+00  0.00000000e+00]
 [ 3.00000000e+01 -2.10000000e+01  4.50000000e+01 -9.90000000e+01]
 [ 1.20000000e+00  8.00000000e-01  6.60000000e+00 -9.00000000e-01]
 [-1.25000000e+01  5.12000000e+00  7.80000000e+00 -4.00000000e-01]]


In [51]:
nump.vstack([e,c])

print()

print(nump.vstack([e,e,c,c]))


[[ 5.15694242e-02  4.80369363e-01  8.91826801e-01  2.25432580e-01]
 [ 6.85245103e-01  7.46917277e-01  1.08849370e-01  4.19857185e-01]
 [ 9.89141431e-01  7.01268176e-01  1.78338767e-01  4.05534271e-01]
 [ 8.19015736e-01  9.56509926e-01  7.49655514e-01  6.88737689e-01]
 [ 5.15694242e-02  4.80369363e-01  8.91826801e-01  2.25432580e-01]
 [ 6.85245103e-01  7.46917277e-01  1.08849370e-01  4.19857185e-01]
 [ 9.89141431e-01  7.01268176e-01  1.78338767e-01  4.05534271e-01]
 [ 8.19015736e-01  9.56509926e-01  7.49655514e-01  6.88737689e-01]
 [-2.90000000e+00 -3.00000000e+00  1.40000000e+00  0.00000000e+00]
 [ 3.00000000e+01 -2.10000000e+01  4.50000000e+01 -9.90000000e+01]
 [ 1.20000000e+00  8.00000000e-01  6.60000000e+00 -9.00000000e-01]
 [-1.25000000e+01  5.12000000e+00  7.80000000e+00 -4.00000000e-01]
 [-2.90000000e+00 -3.00000000e+00  1.40000000e+00  0.00000000e+00]
 [ 3.00000000e+01 -2.10000000e+01  4.50000000e+01 -9.90000000e+01]
 [ 1.20000000e+00  8.00000000e-01  6.60000000e+00 -9.00000000

In [52]:
#Horizontally stacking vectors

print()

print(nump.hstack([e,c]))


[[ 5.15694242e-02  4.80369363e-01  8.91826801e-01  2.25432580e-01
  -2.90000000e+00 -3.00000000e+00  1.40000000e+00  0.00000000e+00]
 [ 6.85245103e-01  7.46917277e-01  1.08849370e-01  4.19857185e-01
   3.00000000e+01 -2.10000000e+01  4.50000000e+01 -9.90000000e+01]
 [ 9.89141431e-01  7.01268176e-01  1.78338767e-01  4.05534271e-01
   1.20000000e+00  8.00000000e-01  6.60000000e+00 -9.00000000e-01]
 [ 8.19015736e-01  9.56509926e-01  7.49655514e-01  6.88737689e-01
  -1.25000000e+01  5.12000000e+00  7.80000000e+00 -4.00000000e-01]]


##### How to load data from a file

In [58]:
nump.genfromtxt('Data.txt', delimiter=',')

OSError: Data.txt not found.

## Pandas

### Loading data into Pandas

In [66]:
import pandas as pd

df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.csv')

print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80   

In [67]:
import pandas as pd

df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.csv')

print(df.head(4)) # Specify the number of rows

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  


In [69]:
import pandas as pd

df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.csv')

print(df.tail(7)) # Specify the number of rows

       #                 Name   Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
793  717              Yveltal     Dark  Flying  126     131       95      131   
794  718     Zygarde50% Forme   Dragon  Ground  108     100      121       81   
795  719              Diancie     Rock   Fairy   50     100      150      100   
796  719  DiancieMega Diancie     Rock   Fairy   50     160      110      160   
797  720  HoopaHoopa Confined  Psychic   Ghost   80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic    Dark   80     160       60      170   
799  721            Volcanion     Fire   Water   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
793       98     99           6       True  
794       95     95           6       True  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6     

In [72]:
import pandas as pd

# df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.csv')

# df_xlsx = pd.read_excel(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.xlsx')

# df_txt = pd.read_txt(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.txt')

df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.txt')

print(df)

    #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0    1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...                                          
1    2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...                                          
2    3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...                                          
3    3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...                                          
4    4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...                                          
..                                                 ...                                          
795  719\tDiancie\tRock\tFairy\t50\t100\t150\t100\t...                                          
796  719\tDiancieMega Diancie\tRock\tFairy\t50\t160...                                          
797  720\tHoopaHoopa Confined\tPsychic\tGhost\t80\t...                                          
798  720\tHoopaHoopa Unbound\t

In [73]:
import pandas as pd

# df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.csv')

# df_xlsx = pd.read_excel(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.xlsx')

# df_txt = pd.read_txt(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.txt')

df = pd.read_csv(r'C:\Users\padra\Desktop\Python Practices\pokemon_data.txt', delimiter='\t')

print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80   

### Reading Data in Pandas

In [74]:
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')


In [75]:
print(df['Name'])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object


In [76]:
print(df['Name'][455:579])

455               Shieldon
456              Bastiodon
457                  Burmy
458    WormadamPlant Cloak
459    WormadamSandy Cloak
              ...         
574                Panpour
575               Simipour
576                  Munna
577               Musharna
578                 Pidove
Name: Name, Length: 124, dtype: object


In [78]:
print(df.Name [455:579]) #With space

455               Shieldon
456              Bastiodon
457                  Burmy
458    WormadamPlant Cloak
459    WormadamSandy Cloak
              ...         
574                Panpour
575               Simipour
576                  Munna
577               Musharna
578                 Pidove
Name: Name, Length: 124, dtype: object


In [79]:
print(df.Name[455:579]) #With no space

455               Shieldon
456              Bastiodon
457                  Burmy
458    WormadamPlant Cloak
459    WormadamSandy Cloak
              ...         
574                Panpour
575               Simipour
576                  Munna
577               Musharna
578                 Pidove
Name: Name, Length: 124, dtype: object


In [81]:
print(df[['Name','Speed','Generation','Attack'][323:557]])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[800 rows x 0 columns]


In [82]:
print(df[['Name','Speed']])

                      Name  Speed
0                Bulbasaur     45
1                  Ivysaur     60
2                 Venusaur     80
3    VenusaurMega Venusaur     80
4               Charmander     65
..                     ...    ...
795                Diancie     50
796    DiancieMega Diancie    110
797    HoopaHoopa Confined     70
798     HoopaHoopa Unbound     80
799              Volcanion     70

[800 rows x 2 columns]


In [83]:
print(df[['Name','Speed','Attack']]) #Printing each column

                      Name  Speed  Attack
0                Bulbasaur     45      49
1                  Ivysaur     60      62
2                 Venusaur     80      82
3    VenusaurMega Venusaur     80     100
4               Charmander     65      52
..                     ...    ...     ...
795                Diancie     50     100
796    DiancieMega Diancie    110     160
797    HoopaHoopa Confined     70     110
798     HoopaHoopa Unbound     80     160
799              Volcanion     70     110

[800 rows x 3 columns]


In [84]:
print(df.iloc[333]) #This is to print out a row. iloc stands for integer location

#                           306
Name          AggronMega Aggron
Type 1                    Steel
Type 2                      NaN
HP                           70
Attack                      140
Defense                     230
Sp. Atk                      60
Sp. Def                      80
Speed                        50
Generation                    3
Legendary                 False
Name: 333, dtype: object


In [85]:
print(df.iloc[333:770])

       #                   Name    Type 1   Type 2   HP  Attack  Defense  \
333  306      AggronMega Aggron     Steel      NaN   70     140      230   
334  307               Meditite  Fighting  Psychic   30      40       55   
335  308               Medicham  Fighting  Psychic   60      60       75   
336  308  MedichamMega Medicham  Fighting  Psychic   60     100       85   
337  309              Electrike  Electric      NaN   40      45       40   
..   ...                    ...       ...      ...  ...     ...      ...   
765  695              Heliolisk  Electric   Normal   62      55       52   
766  696                 Tyrunt      Rock   Dragon   58      89       77   
767  697              Tyrantrum      Rock   Dragon   82     121      119   
768  698                 Amaura      Rock      Ice   77      59       50   
769  699                Aurorus      Rock      Ice  123      77       72   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
333       60       80     50     