In [1]:
import numpy as np

In [2]:
a = np.array([3,7,9])
print(a)

[3 7 9]


In [5]:
b = np.array([[2.1,3.4,5.0],[1,-1,0],[2,9,-3],[4.5,6.2,8.3]])
print(b)

[[ 2.1  3.4  5. ]
 [ 1.  -1.   0. ]
 [ 2.   9.  -3. ]
 [ 4.5  6.2  8.3]]


In [26]:
c = np.array([[-1,1,0,9],[-2.9,-3,1.4,0],[30,-21,45,-99],[3,-7,-9,2],[1.2,0.8,6.6,-0.9],[-12.5,5.12,7.8,-0.4],[3.0,-4.2,-1.1,.6]])
print(c)

[[ -1.     1.     0.     9.  ]
 [ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  3.    -7.    -9.     2.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]
 [  3.    -4.2   -1.1    0.6 ]]


In [13]:
# How to know the dimension of your array

print() # this prints an empty line in Python
a.ndim

1

In [14]:
# How to know the dimension of your array

print() # this prints an empty line in Python
b.ndim

2

In [21]:
# How to know the dimension of your array

print() # this prints an empty line in Python
c.ndim

2

In [15]:
# How to get the shape of your array

a.shape

(3,)

In [16]:
# How to get the shape of your array

b.shape

(4, 3)

In [22]:
# How to get the shape of your array

c.shape

(7, 4)

In [23]:
# How to get the data type

a.dtype

dtype('int32')

In [24]:
# How to get the data type

c.dtype

dtype('float64')

In [25]:
# How to get the data type

b.dtype

dtype('float64')

In [29]:
c = np.array([[-1,1,0,9],[-2.9,-3,1.4,0],[30,-21,45,-99],[3,-7,-9,2],[1.2,0.8,6.6,-0.9],[-12.5,5.12,7.8,-0.4],[3.0,-4.2,-1.1,.6]], dtype= 'int32')
print(c)

# Here, I changed the data type to int from float and also I reduced the size it should take to 4 bytes which is 32 bits (1 byte = 8 bits). 1 bit stores 1 binary which the computer understands i.e. 1 bit stores 0 or 1.

[[ -1   1   0   9]
 [ -2  -3   1   0]
 [ 30 -21  45 -99]
 [  3  -7  -9   2]
 [  1   0   6   0]
 [-12   5   7   0]
 [  3  -4  -1   0]]


In [30]:
# Get itemsize

b.itemsize

8

In [31]:
# Get itemsize

c.itemsize

4

In [32]:
# Get itemsize

a.itemsize

4

In [33]:
# Total number of bytes

c.itemsize * c.size

112

In [34]:
# Total number of bytes (another method)

b.nbytes

96

In [35]:
# Total number of bytes (another method)

c.nbytes

112

In [36]:
c = np.array([[-1,1,0,9],[-2.9,-3,1.4,0],[30,-21,45,-99],[3,-7,-9,2],[1.2,0.8,6.6,-0.9],[-12.5,5.12,7.8,-0.4],[3.0,-4.2,-1.1,.6]])
print(c)

[[ -1.     1.     0.     9.  ]
 [ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  3.    -7.    -9.     2.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]
 [  3.    -4.2   -1.1    0.6 ]]


In [38]:
#Get shape

c.shape

(7, 4)

In [40]:
# Getting specific elements from your array
# [r,c - row, column]

c[1,3]

0.0

In [41]:
# Getting specific elements from your array
# [r,c - row, column]

c[4,2]

6.6

In [42]:
# Getting specific elements from your array
# [r,c - row, column]

c[0,1]

1.0

In [44]:
# Getting specific elements from your array
# [r,c - row, column]

c[-2,-1]

-0.4

In [45]:
# Getting specific elements from your array
# [r,c - row, column]

c[-1,-3]

-4.2

In [43]:
print(c)

[[ -1.     1.     0.     9.  ]
 [ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  3.    -7.    -9.     2.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]
 [  3.    -4.2   -1.1    0.6 ]]


In [46]:
# Getting a specific row

c[0, :]

array([-1.,  1.,  0.,  9.])

In [47]:
# Getting a specific row

c[1, :]

array([-2.9, -3. ,  1.4,  0. ])

In [48]:
# Getting a specific row

c[4, :]

array([ 1.2,  0.8,  6.6, -0.9])

In [53]:
# Getting a specific row

c[-4, :]

array([ 3., -7., -9.,  2.])

In [49]:
# Getting a specific column

c[:, 2]

array([ 0. ,  1.4, 45. , -9. ,  6.6,  7.8, -1.1])

In [50]:
# Getting a specific column

c[:, -1]

array([  9. ,   0. , -99. ,   2. ,  -0.9,  -0.4,   0.6])

In [52]:
# Getting a specific column

c[:, -3]

array([  1.  ,  -3.  , -21.  ,  -7.  ,   0.8 ,   5.12,  -4.2 ])

In [54]:
print(c)

[[ -1.     1.     0.     9.  ]
 [ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  3.    -7.    -9.     2.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]
 [  3.    -4.2   -1.1    0.6 ]]


In [64]:
# Using startindex, endindex and stepsize
#Getting elements from row
c[0, 1:3:1]

array([1., 0.])

In [65]:
# Using startindex, endindex and stepsize
#Getting elements from row
c[0, 0:3:2]

array([-1.,  0.])

In [66]:
# Using startindex, endindex and stepsize
#Getting elements from row
c[-2, 0:-1:2]

array([-12.5,   7.8])

In [67]:
# Using startindex, endindex and stepsize
#Getting elements from column
c[0:3:2, 2]

array([ 0., 45.])

In [68]:
# Using startindex, endindex and stepsize
#Getting elements from column
c[1:-1:1, 2]

array([ 1.4, 45. , -9. ,  6.6,  7.8])

In [69]:
# Using startindex, endindex and stepsize
#Getting elements from column
c[-1:6:2, 3]

array([], dtype=float64)

In [70]:
# Using startindex, endindex and stepsize
#Getting elements from column
c[1:6:2, 3]

array([ 0. ,  2. , -0.4])

In [72]:
c[6,2] = 34
print(c)

[[ -1.     1.     0.     9.  ]
 [ -2.9   -3.     1.4    0.  ]
 [ 30.   -21.    45.   -99.  ]
 [  3.    -7.    -9.     2.  ]
 [  1.2    0.8    6.6   -0.9 ]
 [-12.5    5.12   7.8   -0.4 ]
 [  3.    -4.2   34.     0.6 ]]


In [73]:
c[:, 2] = 11
print(c)

[[ -1.     1.    11.     9.  ]
 [ -2.9   -3.    11.     0.  ]
 [ 30.   -21.    11.   -99.  ]
 [  3.    -7.    11.     2.  ]
 [  1.2    0.8   11.    -0.9 ]
 [-12.5    5.12  11.    -0.4 ]
 [  3.    -4.2   11.     0.6 ]]


In [75]:
c[4, :] = -32
print(c)

[[ -1.     1.    11.     9.  ]
 [ -2.9   -3.    11.     0.  ]
 [ 30.   -21.    11.   -99.  ]
 [  3.    -7.    11.     2.  ]
 [-32.   -32.   -32.   -32.  ]
 [-12.5    5.12  11.    -0.4 ]
 [  3.    -4.2   11.     0.6 ]]


In [79]:
#3D Example
f = np.array([[[1.2,0.3,4.5],[6,-5,0],[1,1,1],[0.2,-6.6,-3.45]],[[4.1,-0.7,-2],[-9,8,-3.3],[0,0,0],[4,-5,2]]])
print(f)

[[[ 1.2   0.3   4.5 ]
  [ 6.   -5.    0.  ]
  [ 1.    1.    1.  ]
  [ 0.2  -6.6  -3.45]]

 [[ 4.1  -0.7  -2.  ]
  [-9.    8.   -3.3 ]
  [ 0.    0.    0.  ]
  [ 4.   -5.    2.  ]]]


In [80]:
#Get a specific element
f[0,1,1]

-5.0

In [81]:
#Get a specific element
f[1,2,0]

0.0

In [82]:
#Get a specific element
f[1,-3,-1]

-3.3

In [83]:
#Get a specific element
f[-2,-1,-0]

0.2

In [84]:
f[0,-1,-0]

#Sample as input 83

0.2

In [85]:
print(f)

[[[ 1.2   0.3   4.5 ]
  [ 6.   -5.    0.  ]
  [ 1.    1.    1.  ]
  [ 0.2  -6.6  -3.45]]

 [[ 4.1  -0.7  -2.  ]
  [-9.    8.   -3.3 ]
  [ 0.    0.    0.  ]
  [ 4.   -5.    2.  ]]]


In [86]:
#Now to get rows and columns from f
# [x,y,z] - The x stands for the index of which array you are choosing out of both arrays, y stands for the row you are choosing and step helps you to narrow down on the column, when you use : (colon), it selects the whole rows or columns or the whole array, depending on how and where you used it.

f[:,0,:]

array([[ 1.2,  0.3,  4.5],
       [ 4.1, -0.7, -2. ]])

In [87]:
#Now to get rows and columns from f
f[:,2,:]

array([[1., 1., 1.],
       [0., 0., 0.]])

In [88]:
#Now to get rows and columns from f
f[:,:,2]

array([[ 4.5 ,  0.  ,  1.  , -3.45],
       [-2.  , -3.3 ,  0.  ,  2.  ]])

In [89]:
f[:,:,-1]

array([[ 4.5 ,  0.  ,  1.  , -3.45],
       [-2.  , -3.3 ,  0.  ,  2.  ]])

In [90]:
f[:,:,-3]

array([[ 1.2,  6. ,  1. ,  0.2],
       [ 4.1, -9. ,  0. ,  4. ]])

In [91]:
f[1,:,2]

array([-2. , -3.3,  0. ,  2. ])

In [92]:
f[0,:,1]

array([ 0.3, -5. ,  1. , -6.6])

In [93]:
print(f)

[[[ 1.2   0.3   4.5 ]
  [ 6.   -5.    0.  ]
  [ 1.    1.    1.  ]
  [ 0.2  -6.6  -3.45]]

 [[ 4.1  -0.7  -2.  ]
  [-9.    8.   -3.3 ]
  [ 0.    0.    0.  ]
  [ 4.   -5.    2.  ]]]


In [94]:
# Replacing elements

f[-2,3,:]

array([ 0.2 , -6.6 , -3.45])

In [97]:
# Replacing elements

f[-2,3,:] = [13,31,33]
print(f)

[[[ 1.2  0.3  4.5]
  [ 6.  -5.   0. ]
  [ 1.   1.   1. ]
  [13.  31.  33. ]]

 [[ 4.1 -0.7 -2. ]
  [-9.   8.  -3.3]
  [ 0.   0.   0. ]
  [ 4.  -5.   2. ]]]


In [98]:
print(f)

[[[ 1.2  0.3  4.5]
  [ 6.  -5.   0. ]
  [ 1.   1.   1. ]
  [13.  31.  33. ]]

 [[ 4.1 -0.7 -2. ]
  [-9.   8.  -3.3]
  [ 0.   0.   0. ]
  [ 4.  -5.   2. ]]]


In [100]:
# Initializing Different Types of ARRAYS

np.zeros(3)

array([0., 0., 0.])

In [107]:
# Initializing Different Types of ARRAYS

np.zeros((7,), dtype=int) # This dtype=int here is to change the output from float to int.

array([0, 0, 0, 0, 0, 0, 0])

In [108]:
np.zeros((4,7)) # 4 by 7 zero matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [111]:
np.zeros((12,37), dtype=int) # 12 by 37 zero matrix with int datatype

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0

In [118]:
# HERE, I want to try to see the whole dataframe. Jupyter is showing me just parts of it because it is large

import pandas as pd
import numpy as np

pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
df

g = np.zeros((133,329), dtype=float) # 133 by 329 zero matrix with int datatype, and I am naming it g
print(g)

#I AM NOT GETTING THIS!

OptionError: "No such keys(s): 'display.height'"

In [123]:
g = np.zeros((133,329), dtype=float) # 133 by 329 zero matrix with int datatype, and I am naming it g
print(g)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [119]:
np.zeros((4,3,2,3), dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]]])

In [120]:
np.zeros((4,3,2,3), dtype=float)

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [121]:
np.ones((6,5,3,5), dtype=int)

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [

In [122]:
np.ones((6,5,3,5), dtype=float)

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1

In [124]:
np.ones((6,5,3,5), dtype='float32')

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1

In [125]:
np.ones((2,5,3,5), dtype='int64')

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int64)

In [128]:
# matrix of any other number

np.full((4,7), 65.23)

array([[65.23, 65.23, 65.23, 65.23, 65.23, 65.23, 65.23],
       [65.23, 65.23, 65.23, 65.23, 65.23, 65.23, 65.23],
       [65.23, 65.23, 65.23, 65.23, 65.23, 65.23, 65.23],
       [65.23, 65.23, 65.23, 65.23, 65.23, 65.23, 65.23]])

In [131]:
# matrix of any other number

np.full(((13,8), 65.23), dtype='int64')

TypeError: full() missing 1 required positional argument: 'fill_value'

In [133]:
# matrix of any other number

np.full((9,7), 4.0007)

array([[4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007],
       [4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007, 4.0007]])

In [139]:
# matrix or array of any other number like one that had been previously created

np.full_like(f.shape, 0.00045)

array([0, 0, 0])

In [136]:
# matrix or array of any other number like one that had been previously created

np.full_like(g.shape, 1.36)

array([1, 1])

In [137]:
# matrix or array of any other number like one that had been previously created.

np.full_like(g, 1.36)

array([[1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       ...,
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36]])

In [140]:
# matrix or array of any other number like one that had been previously created

np.full_like(f, 0.00045)

array([[[0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045]],

       [[0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045]]])

In [141]:
# matrix or array of any other number like one that had been previously created. Another way of doing Input 140

np.full(f.shape, 0.00045)

array([[[0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045]],

       [[0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045],
        [0.00045, 0.00045, 0.00045]]])

In [142]:
# matrix or array of any other number like one that had been previously created. Another way of doing Input 137.

np.full_like(g, 1.36)

array([[1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       ...,
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36],
       [1.36, 1.36, 1.36, ..., 1.36, 1.36, 1.36]])

In [143]:
# Initializing arrays of random decimals

np.random.rand(3,5)

array([[0.48469272, 0.20938572, 0.25808728, 0.7026451 , 0.41522076],
       [0.97938469, 0.7209457 , 0.83354041, 0.37796714, 0.60831635],
       [0.02457571, 0.9910642 , 0.06272022, 0.97460139, 0.9534683 ]])

In [144]:
# Initializing arrays of random decimals

np.random.rand(7,3,5)

array([[[0.85725152, 0.78134617, 0.78040576, 0.77362564, 0.57380093],
        [0.27954818, 0.91626435, 0.78995808, 0.42779989, 0.7069331 ],
        [0.70510707, 0.97740459, 0.32146919, 0.96189425, 0.44815814]],

       [[0.79128709, 0.58375523, 0.73004327, 0.7977652 , 0.45856608],
        [0.65071179, 0.12101938, 0.81369861, 0.34617537, 0.39971154],
        [0.78468925, 0.88509829, 0.62558479, 0.92935947, 0.88282367]],

       [[0.6747689 , 0.33418368, 0.21275229, 0.89987881, 0.8612621 ],
        [0.33473641, 0.67393517, 0.5611968 , 0.580092  , 0.13549753],
        [0.31438897, 0.93775786, 0.88538985, 0.77350168, 0.13017565]],

       [[0.6606819 , 0.94746671, 0.01438112, 0.79369237, 0.05746821],
        [0.76090129, 0.65737018, 0.31249623, 0.8853855 , 0.22139068],
        [0.80940285, 0.3200548 , 0.08264823, 0.29006349, 0.59123746]],

       [[0.23285308, 0.37841348, 0.07920417, 0.58677022, 0.9524742 ],
        [0.23247824, 0.52689969, 0.63551482, 0.24557259, 0.32304388],
        [0.8

In [145]:
# Initializing arrays of random decimals that is like a previously made array

np.random.random_sample(g.shape)

array([[0.88800354, 0.39793273, 0.43015593, ..., 0.84809793, 0.33255815,
        0.1793373 ],
       [0.303352  , 0.21857165, 0.54507611, ..., 0.05482512, 0.30177301,
        0.53246297],
       [0.56160549, 0.03623851, 0.99004095, ..., 0.18856869, 0.2269439 ,
        0.58424797],
       ...,
       [0.13125497, 0.15438798, 0.30508547, ..., 0.4294783 , 0.37263853,
        0.80883386],
       [0.57597547, 0.38145128, 0.24289238, ..., 0.90135466, 0.86008021,
        0.29164123],
       [0.94623507, 0.85872338, 0.90119004, ..., 0.95546165, 0.06264948,
        0.22266205]])

In [146]:
# Initializing arrays of random decimals that is like a previously made array

np.random.random_sample(f.shape)

array([[[0.34788355, 0.69609599, 0.21723914],
        [0.40747922, 0.82383053, 0.79960388],
        [0.0403017 , 0.00566736, 0.41029691],
        [0.74241015, 0.72036265, 0.0724269 ]],

       [[0.80941167, 0.10388445, 0.27256605],
        [0.77323223, 0.50896744, 0.10959162],
        [0.04341737, 0.86761501, 0.59912355],
        [0.65278227, 0.30125723, 0.16761648]]])

In [161]:
# Initializing arrays of random integers

np.random.randint(5) #This gives us just a random integer that is less than 5.

4

In [164]:
# Initializing arrays of random integers

np.random.randint(9, size=(5,6))   #This gives us an array of integers, with the specified rows and columns, less than 9.

array([[1, 0, 4, 6, 5, 4],
       [8, 6, 6, 5, 4, 4],
       [5, 3, 1, 7, 6, 8],
       [8, 0, 5, 5, 0, 3],
       [2, 8, 1, 2, 0, 2]])

In [165]:
# Initializing arrays of random integers

np.random.randint(-8,14, size=(8,12))   #This gives us an array of integers, with the specified rows and columns, within the range of -8 and 14.

array([[ 0,  8,  8, 11,  8,  7, -6, -5, 10,  7, 10,  9],
       [-6,  8, 10, 11, 11,  9, 12, -5,  9, -1,  2, 11],
       [ 2, -1, -7,  3,  5, 12, -6, -2,  0,  0,  8, -2],
       [-6,  1, -3, 11, -3, 12, -7,  7,  5, 12, -6, -8],
       [ 3, 10,  1, 11, -3, -3, 10, -1, 10,  9,  2,  2],
       [ 8,  1, 13, -8,  2, 13,  1, -6, -3, -5,  0,  0],
       [-3,  5, -8, -1,  9,  1, -4,  0, 13, -7, -2, -2],
       [ 7, 10,  0,  2, 13,  9, -1, -5, -1,  7, -1,  4]])

In [166]:
# Initializing arrays of random integers

np.random.randint(-8,14, size=(4,8,12))   #This gives us an array of integers, with the specified rows and columns (4 times, basically 3D arrays), within the range of -8 and 14.

array([[[ 3,  8, 12,  1, 11,  7, -5, -2, -6,  4, 10,  2],
        [ 1, -3,  6,  2,  2,  3, -4,  1, -3, -4, 10, 11],
        [11, 11, -4,  7, 11, -8,  0,  7,  8,  6, 12,  5],
        [ 4,  3,  6,  9,  5,  1, 13,  1, -2, -7, 13,  3],
        [ 7,  5, -8, -3,  9, -4, -3, 13,  0, 13,  2,  5],
        [12, -1,  7, -2, -7,  4, 11,  8, 12, -3, -4, -8],
        [-2, -6, -7,  8, -1,  1, -1, 10, -7, 13,  1, 11],
        [ 3,  8, 11, 10, 10, -1,  0,  4,  7,  2,  7,  1]],

       [[ 3,  6,  9, 11, -5, -6,  9, -1, -4, -2,  9, -3],
        [-2,  5,  4, -3, -2, -4, -6, -3,  3,  2, 10, 12],
        [-7,  3,  8, 10,  9,  3, -5, -4,  3,  2,  5, 13],
        [-6, -2, -1, -3,  2, -4, -2, -8, -4, 12, -2, 13],
        [ 2, -6,  6, -6,  4, -6,  2,  9,  3,  1, -5, -7],
        [ 5,  7,  7, -4,  7,  5,  8,  3, 12, 12,  9, -3],
        [ 0, -4,  5, 10, -8,  9,  9, -1, 10, -3,  6, -7],
        [-1,  2, 13,  8, 12,  9, -8,  3,  7, -7,  8,  5]],

       [[-1,  7, -3,  3, -1, -4, -2, -6, 13, 10, -7,  0],
        [1

In [167]:
# Initializing an identity matrix

np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [168]:
# Initializing an identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
# Initializing an identity matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [170]:
# Initializing an identity matrix, making the elements to be integers.

np.identity(7, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [171]:
# Initializing an identity matrix, making the elements to be integers.

np.identity(25, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      

In [172]:
# Initializing an identity matrix, making the elements to be boolean.

np.identity(14, dtype=bool)

array([[ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        F

In [187]:
sample1 = np.zeros([9,9], dtype=int) #I am trying to carry out an exercise.
print(sample1)

print()

change1 = np.ones([6,6], dtype=int)

change1[2,3] = -1
change1[0,-4] = -3
change1[-2,-1] = 9

print(change1)

print()

sample1[2:8,1:7] = change1

print(sample1)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]

[[ 1  1 -3  1  1  1]
 [ 1  1  1  1  1  1]
 [ 1  1  1 -1  1  1]
 [ 1  1  1  1  1  1]
 [ 1  1  1  1  1  9]
 [ 1  1  1  1  1  1]]

[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  1  1 -3  1  1  1  0  0]
 [ 0  1  1  1  1  1  1  0  0]
 [ 0  1  1  1 -1  1  1  0  0]
 [ 0  1  1  1  1  1  1  0  0]
 [ 0  1  1  1  1  1  9  0  0]
 [ 0  1  1  1  1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


## Using Markdown

### Copying arrays carefully

In [ ]:
print(a) #Array a from up there!

q = a.copy() #Using this style will ensure that the first array i.e the array being copied is not altered.

q[1] = -1.34

print()

print(q)

[3 7 9]

[ 3 -1  9]
